kind: pipeline
type: docker
name: default

trigger:
  branch:
  - main

steps:
#  - name: test server
#    depends_on:
#    - clone
#    image: node:16
#    commands:
#    - cd server
#    - yarn install
#    - yarn test

  - name: build server (dry run)
    image: plugins/docker
    settings:
      dry_run: true
      context: server
      dockerfile: server/Dockerfile
      username: octocat
      repo: octocat/atlas-search-server
      tags:
      - latest
    when:
      event:
      - pull_request

  - name: build client (dry run)
    image: plugins/docker
    settings:
      dry_run: true
      context: client
      dockerfile: client/Dockerfile
      build_args:
      - SERVER_URI="http://example.com:5001"
      username: octocat
      repo: octocat/atlas-search-client
      tags:
      - latest
    when:
      event:
      - pull_request

  - name: build server
    image: plugins/docker
    settings:
      context: server
      dockerfile: server/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_repo_server
      tags:
      - latest
    when:
      event:
      - push
      branch:
      - main

  - name: build client
    image: plugins/docker
    settings:
      context: client
      dockerfile: client/Dockerfile
      build_args_from_env: SERVER_URI
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_repo_client
      tags:
      - latest
    when:
      event:
      - push
      branch:
      - main
